### ISSUE TITLE
Optisch evtl. noch folgendes verbessern

### ISSUE THREAD

**Issue by iceman-fx** [novinet-git/nv_modulepreview#4]
- Overlay etwas dunkler, da man den Schließen Button kaum erkennt
- Schließen Button etwas größer
- Mehr Abstand zum Rand auf kleineren Displays
- Hovereffekt einfügen für "Einfügen Inhaltsblock"
- alle Boxen sollte die gleiche Höhe haben, egal wie lang der Titeltext ist

**Comment by novinet-git** [comment]
erledigt
