### ISSUE TITLE
wenn Bilder verbergen aktiv, da "flattern" die Textboxen in der Höhe

### ISSUE THREAD

**Issue by iceman-fx** [novinet-git/nv_modulepreview#6]
analog der Boxen mit Bild, sollte die Höhe evtl. immer gleich sein.

![1](https://user-images.githubusercontent.com/4291047/176364691-234a8be9-0474-4b7c-aa4d-58b973a1afd1.PNG)

**Comment by novinet-git** [comment]
Ist mit der neuen Version erledigt
