### ISSUE TITLE
Wenn "Modulauswahl (System) nur Gridblock anzeigen" aktiv, dann sofort den Gridblock einfügen

### ISSUE THREAD

**Issue by iceman-fx** [novinet-git/nv_modulepreview#8]
Wenn man diesen Modus aktiv hat, dann ist der Zwischenschritt mit der Anzeige der Modulvorschau eigentlich überflüssig, da ich eh nur 1 Modul zur Auswahl habe.
Hier könnte man gleich das GB-Modul einladen und damit den Zwischenschritt sparen.

**Comment by novinet-git** [comment]
Wenn es nur ein Modul gibt UND kein Modul über Copy & Paste zur Verfügung steht wird das jetzt so gemacht
